### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by lesander** [marijnpool/Magister-2-Google-Calendar#1]
Hi Marijn,

Tof dat je aan dit project bent begonnen voor je school. En al helemaal goed dat je het ook open source maakt. 

Klein detail misschien, maar je hebt de `LICENSE` van Magister Calendar aangepast in je fork/project.

Magister Calendar is open source gemaakt door mij (en je mag er zowat alles mee doen, zie de [MIT License](https://git.io/magister-calendar-license)), onder voorwaarde dat de LICENSE intact blijft.

```
Copyright (c) 2015-2016 Sander Laarhoven
[...]
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
[...]
```

Met vriendelijke groet,
Sander

**Comment by marijnpool** [comment]
Beste Sander 
Ik zal jou licence dan toevoegen aan deze repo. Is dat oké voor jou aangezien de code van jou nu nog bijna het zelfde is maar wel veranderd gaat worden.

**Comment by lesander** [comment]
Hi Marijn,

Alles is goed nu 😄 . Het enige puntje was de licentie die ontbrak.

**Comment by marijnpool** [comment]
Hi Sander 
Oké mooi
